version: "3.9"

services:
  api:
    image: ${DOCKERHUB_USERNAME:-local}/housing-api:latest
    build:
    context: .
    dockerfile:Dockerfile
    container_name: iris-mlops-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mlflow
    environment:
      # Use Docker bridge gateway IP to access MLflow on the host
      - MLFLOW_TRACKING_URI=http://127.0.0.1:5000/
# The Prometheus Monitoring Service
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - iris-mlops-api
  
# The Grafana Dashboard Service
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  grafana_data: